GET http://localhost:3001/api/appointments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NjRmMjU3YTU5ODA0M2IzOWU0YjZiNGMiLCJpYXQiOjE3MTY2NDkxMzMsImV4cCI6MTcxNjY1MjczM30.YXGE3hy2Vc6D3CGzHlKEtsppNI_nbQID7k6q09FXFOk
